### ISSUE TITLE
Ability to provide Filters and Transforms

### ISSUE THREAD

**Issue by AV25242** [mgroves/SqlServerToCouchbase#1]
As with any migration platform need to filter / transform data might be necessary. For instance it might be necessary not to migrate certain fields due to security reasons , fields like SSN, DOB etc. Even more you might want to only bring in most recent data probably by filtering by created date greater than a particular date.

**Comment by mgroves** [comment]
What would be a good look for this API? Maybe an optional list of objects passed into `Migrate` when copying data? Each filter contains TableName, a Transform (Func) and/or Filter (Func<bool>)? Transform would transform the row, Filter would determine whether or not to copy to the row at all. Something like:

```
public class CopyDataSpec
{
  public string TableName {get;set;}
  public Func<dynamic> Transform (dynamic row);
  public Func<bool> IncludeFilter(dynamic row);
}
```

Then `List<CopyDataSpec>` could be (optionally) passed in to `Migrate`

Or it could be an `abstract` base class instead of defining `Func`s. I'd have to try both out to see if one felt more elegant than the other, but either way a spec is associated with a table and can transform and/or opt-out each row of data from being copied over.

Thoughts?

**Comment by AV25242** [comment]
I like it , the only thing I was wondering is would it not be a List of Transforms and a List of Filters ? 

in the sense each row can go through multiple transform functions ( kind of like a chain of responsibility/ command pattern) 
and filter would be also the same way, I might want to filter on multiple fields this will be extremely useful if I am planning to decompose a table into multiple collection 
Say I have a table with regions , east, west,  north and south and within region I have departments and I want to filter those rows by region and department to go into its specific collection

**Comment by mgroves** [comment]
So maybe it becomes List<Func<dynamic>> (or List<CopyDataSpec> with `abstract` approach). I can see the value in that approach.

As far as dividing up a table into _multiple_ collections, that's something that could be done *after* moving the data over to Couchbase, and probably more efficiently that way. Additionally, a more complex mapping would have to be entered. It's not just putting data into a collection by naming convention, but now I have to explicitly define `table -> collection1 when X`, `table -> collection2 when Y`, etc. Unless you have a convention in mind?

Also, that sort of use case might be better served by kafka or other connector than a "one shot" migration tool like this. And that's starting to get into "level 2" migration, where you start to think about changing the structure of the data to be more optimized for Couchbase/JSON.

**Comment by AV25242** [comment]
I agree that it can be considered as level 2 migration,  not all companies my be vested in using Kafka connectors but yah any it can be thought of as an option to do migration, the tasks can be used to do transformations. 

The reason I think Filters being a list would make sense is that I can see a user filtering data on multiple fields or same fields
the use case that I gave might not be trivial , but say I want get data from the database where created date is between 2 dates  I need 2 filters 

Where createdate > ? and createdate <= ?

**Comment by mgroves** [comment]
Yes, I agree filters would be useful for date range limiting, transforms would be useful for PII, and probably dozens of other uses for both.

**Comment by mgroves** [comment]
I'm working on this now. I've created a base class that can be overwritten and used with C# and/or SQL in any combination to perform filtering and transforming. The default class is what's used now, but it can be inherited and overwritten. This is my 2nd or 3rd design iteration, and I've yet to integrate it and try it out (I plan to do so with a Dictionary that maps a pipeline to a table). But I wanted to get some thoughts on naming and design (if you have any).

```
public class SqlPipelineDefault
{
    public SqlPipelineDefault(string schemaName, string tableName)
    {
        // select every column and every row
        Query = $@"SELECT * FROM [{schemaName}].[{tableName}]";
    }

    public virtual string Query { get; }

    public virtual bool IsIncluded(dynamic row)
    {
        // filters nothing
        return true;
    }

    public virtual dynamic Transform(dynamic row)
    {
        // transforms nothing
        return row;
    }
}
```

So for instance, if I wanted to filter by a date, I could do either of:

```
    public class MyCustomCsharpFilter : SqlPipelineDefault
    {
        public MyCustomCsharpFilter(string schemaName, string tableName) : base(schemaName, tableName)
        {
        }

        public override bool IsIncluded(dynamic row)
        {
            DateTime modifiedDate = row.ModifiedDate;
            return modifiedDate >= new DateTime(2014, 05, 26);
        }
    }
```

or

```
    public class MyOtherCustomSqlFilter : SqlPipelineDefault
    {
        private readonly string _schemaName;
        private readonly string _tableName;

        public MyOtherCustomSqlFilter(string schemaName, string tableName) : base(schemaName, tableName)
        {
            _schemaName = schemaName;
            _tableName = tableName;
        }

        public override string Query => $@"SELECT * FROM [{_schemaName}].[{_tableName}] WHERE ModifiedDate >= '2014-05-26'";
    }
```

With the latter probably being the better choice in most situations, but not always. C# might be the better choice in some situations.

And then to add it to the migration process would be:

`pipelineDictionary.Add("Person.Address",typeof(MyOtherCustomSqlFilter));`

(or something like that--haven't figured that part out yet)

**Comment by mgroves** [comment]
Here's the pull request, let me know what you think - https://github.com/mgroves/SqlServerToCouchbase/pull/2

**Comment by mgroves** [comment]
:shipit:
